-- MySQL Script generated by MySQL Workbench
-- Fri Feb 15 20:22:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotel_reservation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_reservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_reservation` DEFAULT CHARACTER SET utf8 ;
USE `hotel_reservation` ;

-- -----------------------------------------------------
-- Table `hotel_reservation`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_reservation`.`hotel` ;

CREATE TABLE IF NOT EXISTS `hotel_reservation`.`hotel` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotel_reservation`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_reservation`.`user` ;

CREATE TABLE IF NOT EXISTS `hotel_reservation`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotel_reservation`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_reservation`.`room` ;

CREATE TABLE IF NOT EXISTS `hotel_reservation`.`room` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `discount` INT(11) NULL DEFAULT NULL,
  `is_free` BIT(1) NULL DEFAULT NULL,
  `number` VARCHAR(255) NULL DEFAULT NULL,
  `price_per_day` DECIMAL(19,2) NULL DEFAULT NULL,
  `roominess` INT(11) NULL DEFAULT NULL,
  `hotel` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKtk0m49c4l9t3rppjso6909g4m` (`hotel` ASC),
  CONSTRAINT `FKtk0m49c4l9t3rppjso6909g4m`
    FOREIGN KEY (`hotel`)
    REFERENCES `hotel_reservation`.`hotel` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotel_reservation`.`orderr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_reservation`.`orderr` ;

CREATE TABLE IF NOT EXISTS `hotel_reservation`.`orderr` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `begin_date` TINYBLOB NULL DEFAULT NULL,
  `end_date` TINYBLOB NULL DEFAULT NULL,
  `is_paid` BIT(1) NULL DEFAULT NULL,
  `room_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKexxfs70qtk7ys0oqsgqtjxqvo` (`room_id` ASC),
  INDEX `FK3dxi3kixhle9o5quc89rmtu7k` (`user_id` ASC),
  CONSTRAINT `FK3dxi3kixhle9o5quc89rmtu7k`
    FOREIGN KEY (`user_id`)
    REFERENCES `hotel_reservation`.`user` (`id`),
  CONSTRAINT `FKexxfs70qtk7ys0oqsgqtjxqvo`
    FOREIGN KEY (`room_id`)
    REFERENCES `hotel_reservation`.`room` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;